#!/usr/bin/env python3
"""
Fallback SQLite to MySQL dump script (Python-only).
Usage: python3 scripts/dump_sqlite_py.py [SQLITE_DB_PATH] [OUTPUT_SQL_FILE]

This script mimics the behavior of `sqlite3 .dump` but sanitizes the output
for MySQL compatibility directly, without requiring the sqlite3 CLI.
"""

import sqlite3
import sys
import re

def dump_to_mysql(db_path, output_path):
    conn = sqlite3.connect(db_path)
    # Allow accessing columns by name
    conn.row_factory = sqlite3.Row

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("-- MySQL Compatible Dump generated by dump_sqlite_py.py\n")
        f.write("SET FOREIGN_KEY_CHECKS=0;\n\n")

        # Get all tables
        tables = conn.execute("SELECT name, sql FROM sqlite_master WHERE type='table' AND name != 'sqlite_sequence'").fetchall()

        for table in tables:
            table_name = table['name']
            create_sql = table['sql']

            # Sanitize CREATE statement
            # 1. Replace AUTOINCREMENT
            create_sql = create_sql.replace("AUTOINCREMENT", "AUTO_INCREMENT")
            # 2. Replace INTEGER PRIMARY KEY with INTEGER PRIMARY KEY AUTO_INCREMENT
            # (Note: In SQLite, INTEGER PRIMARY KEY is auto-increment by default, explicit AUTOINCREMENT is distinct, but for MySQL we want explicit)
            # Simple regex replace might be brittle, but sufficient for this app's schema
            create_sql = re.sub(r'INTEGER\s+PRIMARY\s+KEY(?!\s+AUTO_INCREMENT)', 'INTEGER PRIMARY KEY AUTO_INCREMENT', create_sql, flags=re.IGNORECASE)

            # 3. Quote identifiers? SQLite dump usually preserves them.
            # Let's stick to standard SQL.

            f.write(f"DROP TABLE IF EXISTS `{table_name}`;\n")
            f.write(f"{create_sql};\n\n")

            # Dump Data
            rows = conn.execute(f"SELECT * FROM `{table_name}`").fetchall()
            if rows:
                f.write(f"INSERT INTO `{table_name}` VALUES\n")
                values_list = []
                for row in rows:
                    # Format values
                    vals = []
                    for item in row:
                        if item is None:
                            vals.append("NULL")
                        elif isinstance(item, (int, float)):
                            vals.append(str(item))
                        else:
                            # Escape string for SQL
                            # Basic escape: replace ' with ''
                            safe_str = str(item).replace("'", "''").replace("\\", "\\\\")
                            vals.append(f"'{safe_str}'")
                    values_list.append(f"({', '.join(vals)})")

                f.write(",\n".join(values_list))
                f.write(";\n\n")

        f.write("SET FOREIGN_KEY_CHECKS=1;\n")

    conn.close()
    print(f"Dumped {len(tables)} tables to {output_path}")

if __name__ == '__main__':
    db_path = sys.argv[1] if len(sys.argv) > 1 else 'quran_center.db'
    output_path = sys.argv[2] if len(sys.argv) > 2 else 'dump_mysql.sql'

    try:
        dump_to_mysql(db_path, output_path)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
